name: Build Sequence

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  prepare:
    name: Prepare Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_ref.outputs.version }}
      ref: ${{ steps.get_ref.outputs.ref }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version and ref
        id: get_ref
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            REF=$GITHUB_REF
          else
            VERSION="main"
            REF="refs/heads/main"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "ref=${REF}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"
          echo "Using ref: ${REF}"

  linux-build:
    name: Build Linux
    needs: [prepare]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Run Linux build
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting Linux build..."
          gh workflow run linux.yml \
            --ref ${{ needs.prepare.outputs.ref }} \
            --raw-field version=${{ needs.prepare.outputs.version }}
          
          # 等待工作流启动
          sleep 5
          
          # 获取最新运行的 ID
          RUN_ID=$(gh run list --workflow=linux.yml --limit=1 --json databaseId --jq '.[0].databaseId')
          echo "Linux build run ID: ${RUN_ID}"
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          
          # 等待工作流完成
          gh run watch ${RUN_ID}

  macos-build:
    name: Build macOS
    needs: [prepare, linux-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Run macOS build
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting macOS build..."
          gh workflow run macos.yml \
            --ref ${{ needs.prepare.outputs.ref }} \
            --raw-field version=${{ needs.prepare.outputs.version }}
          
          # 等待工作流启动
          sleep 5
          
          # 获取最新运行的 ID
          RUN_ID=$(gh run list --workflow=macos.yml --limit=1 --json databaseId --jq '.[0].databaseId')
          echo "macOS build run ID: ${RUN_ID}"
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          
          # 等待工作流完成
          gh run watch ${RUN_ID}

  windows-build:
    name: Build Windows
    needs: [prepare, macos-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Run Windows build
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting Windows build..."
          gh workflow run windows.yml \
            --ref ${{ needs.prepare.outputs.ref }} \
            --raw-field version=${{ needs.prepare.outputs.version }}
          
          # 等待工作流启动
          sleep 5
          
          # 获取最新运行的 ID
          RUN_ID=$(gh run list --workflow=windows.yml --limit=1 --json databaseId --jq '.[0].databaseId')
          echo "Windows build run ID: ${RUN_ID}"
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          
          # 等待工作流完成
          gh run watch ${RUN_ID}

  godot-plugin:
    name: Build Godot Plugin
    needs: [prepare, windows-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Run Godot Plugin build
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting Godot Plugin build..."
          gh workflow run godot_plugin.yml \
            --ref ${{ needs.prepare.outputs.ref }} \
            --raw-field version=${{ needs.prepare.outputs.version }}
          
          # 等待工作流启动
          sleep 5
          
          # 获取最新运行的 ID
          RUN_ID=$(gh run list --workflow=godot_plugin.yml --limit=1 --json databaseId --jq '.[0].databaseId')
          echo "Godot Plugin build run ID: ${RUN_ID}"
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          
          # 等待工作流完成
          gh run watch ${RUN_ID}

  create-release:
    name: Create Release
    needs: [prepare, godot-plugin]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Download artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts
          
          echo "Downloading Linux artifacts from run ${{ needs.linux-build.outputs.run_id }}..."
          gh run download ${{ needs.linux-build.outputs.run_id }} --dir artifacts
          
          echo "Downloading macOS artifacts from run ${{ needs.macos-build.outputs.run_id }}..."
          gh run download ${{ needs.macos-build.outputs.run_id }} --dir artifacts
          
          echo "Downloading Windows artifacts from run ${{ needs.windows-build.outputs.run_id }}..."
          gh run download ${{ needs.windows-build.outputs.run_id }} --dir artifacts
          
          echo "Downloading Godot Plugin artifacts from run ${{ needs.godot-plugin.outputs.run_id }}..."
          gh run download ${{ needs.godot-plugin.outputs.run_id }} --dir artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ needs.prepare.outputs.version }}
          
          # 创建 release
          gh release create ${VERSION} \
            --title "Release ${VERSION}" \
            --notes "Release ${VERSION}" \
            ./artifacts/*

  cleanup:
    name: Cleanup
    needs: [godot-plugin, create-release]
    runs-on: ubuntu-latest
    if: always()  # 即使其他作业失败也运行
    permissions:
      actions: write  # 需要此权限来删除工作流运行记录        

    steps:
      - uses: actions/checkout@v3
      
      - name: Delete old workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 5  # 保留5天的构建记录
          save_min_runs_number: 3  # 至少保留3次运行记录
