name: Godot Protobuf GDScript Plugin Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  PLUGIN_NAME: protobuf-gdscript

jobs:
  package-plugin:
    name: Package Godot Protobuf GDScript Plugin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Plugin Package
      run: |
        VERSION="${{ inputs.version }}"
        PACKAGE_NAME="${{ env.PLUGIN_NAME }}-godot-plugin-${VERSION}"
        mkdir -p ${PACKAGE_NAME}
        cp -r addons ${PACKAGE_NAME}/
        zip -r ${PACKAGE_NAME}.zip ${PACKAGE_NAME}

    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PLUGIN_NAME }}-godot-plugin-${{ inputs.version }}
        path: ${{ env.PLUGIN_NAME }}-godot-plugin-*.zip
        retention-days: 14
