name: Release Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="main"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

  linux-build:
    needs: prepare
    permissions:
      contents: write
    uses: ./.github/workflows/linux.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  macos-build:
    needs: [prepare, linux-build]
    permissions:
      contents: write
    uses: ./.github/workflows/macos.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  windows-build:
    needs: [prepare, macos-build]
    permissions:
      contents: write
    uses: ./.github/workflows/windows.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  godot-plugin:
    needs: [prepare, windows-build]
    permissions:
      contents: write
    uses: ./.github/workflows/godot_plugin.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  cleanup:
    needs: [godot-plugin]
    runs-on: ubuntu-latest
    if: always()  # 即使其他作业失败也运行
    permissions:
      actions: write  # 需要此权限来删除工作流运行记录

    steps:
    - name: Delete old workflow runs
      uses: dmvict/clean-workflow-runs@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        save_period: 5  # 保留5天的构建记录
        save_min_runs_number: 3  # 至少保留3次运行记录
