name: Release Workflow

on:
 # push:
 #   tags:
 #     - 'v*'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="main"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

  linux-build:
    needs: prepare
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger Linux workflow
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/linux.yml/dispatches \
            -d '{"ref":"${{ github.ref }}","inputs":{"version":"${{ needs.prepare.outputs.version }}"}}')
          
          # 获取最新的运行 ID
          sleep 5  # 等待工作流启动
          RUN_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/linux.yml/runs?per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Wait for Linux workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            STATUS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
              | jq -r '.status')
            
            echo "Workflow status: ${STATUS}"
            if [ "${STATUS}" = "completed" ]; then
              CONCLUSION=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
                | jq -r '.conclusion')
              
              if [ "${CONCLUSION}" = "success" ]; then
                echo "Workflow completed successfully"
                break
              else
                echo "Workflow failed with conclusion: ${CONCLUSION}"
                exit 1
              fi
            fi
            sleep 10
          done

  macos-build:
    needs: [prepare, linux-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger macOS workflow
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/macos.yml/dispatches \
            -d '{"ref":"${{ github.ref }}","inputs":{"version":"${{ needs.prepare.outputs.version }}"}}')
          
          # 获取最新的运行 ID
          sleep 5  # 等待工作流启动
          RUN_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/macos.yml/runs?per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Wait for macOS workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            STATUS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
              | jq -r '.status')
            
            echo "Workflow status: ${STATUS}"
            if [ "${STATUS}" = "completed" ]; then
              CONCLUSION=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
                | jq -r '.conclusion')
              
              if [ "${CONCLUSION}" = "success" ]; then
                echo "Workflow completed successfully"
                break
              else
                echo "Workflow failed with conclusion: ${CONCLUSION}"
                exit 1
              fi
            fi
            sleep 10
          done

  windows-build:
    needs: [prepare, macos-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger Windows workflow
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/windows.yml/dispatches \
            -d '{"ref":"${{ github.ref }}","inputs":{"version":"${{ needs.prepare.outputs.version }}"}}')
          
          # 获取最新的运行 ID
          sleep 5  # 等待工作流启动
          RUN_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/windows.yml/runs?per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Wait for Windows workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            STATUS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
              | jq -r '.status')
            
            echo "Workflow status: ${STATUS}"
            if [ "${STATUS}" = "completed" ]; then
              CONCLUSION=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
                | jq -r '.conclusion')
              
              if [ "${CONCLUSION}" = "success" ]; then
                echo "Workflow completed successfully"
                break
              else
                echo "Workflow failed with conclusion: ${CONCLUSION}"
                exit 1
              fi
            fi
            sleep 10
          done

  godot-plugin:
    needs: [prepare, windows-build]
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.trigger.outputs.run_id }}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger Godot Plugin workflow
        id: trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/godot_plugin.yml/dispatches \
            -d '{"ref":"${{ github.ref }}","inputs":{"version":"${{ needs.prepare.outputs.version }}"}}')
          
          # 获取最新的运行 ID
          sleep 5  # 等待工作流启动
          RUN_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/godot_plugin.yml/runs?per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Wait for Godot Plugin workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            STATUS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
              | jq -r '.status')
            
            echo "Workflow status: ${STATUS}"
            if [ "${STATUS}" = "completed" ]; then
              CONCLUSION=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.trigger.outputs.run_id }}" \
                | jq -r '.conclusion')
              
              if [ "${CONCLUSION}" = "success" ]; then
                echo "Workflow completed successfully"
                break
              else
                echo "Workflow failed with conclusion: ${CONCLUSION}"
                exit 1
              fi
            fi
            sleep 10
          done

  cleanup:
    needs: [godot-plugin]
    runs-on: ubuntu-latest
    if: always()  # 即使其他作业失败也运行
    permissions:
      actions: write  # 需要此权限来删除工作流运行记录

    steps:
    - name: Delete old workflow runs
      uses: dmvict/clean-workflow-runs@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        save_period: 5  # 保留5天的构建记录
        save_min_runs_number: 3  # 至少保留3次运行记录
