name: Release Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v0.0.1'

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

  linux-build:
    needs: prepare
    uses: ./.github/workflows/linux.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  macos-build:
    needs: [prepare, linux-build]
    uses: ./.github/workflows/macos.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  windows-build:
    needs: [prepare, macos-build]
    uses: ./.github/workflows/windows.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  godot-plugin:
    needs: [prepare, windows-build]
    uses: ./.github/workflows/godot_plugin.yml
    with:
      version: ${{ needs.prepare.outputs.version }}

  create-release:
    needs: [prepare, linux-build, macos-build, windows-build, godot-plugin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/**/*
          name: Release ${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
